spring.application.name=product
spring.datasource.url=jdbc:mysql://localhost:3306/dwb2026_2
spring.datasource.username=root
spring.datasource.password=sql#04
spring.datasource.driverClassName=com.mysql.jdbc.Driver

# Carpetas de archivos
app.upload.dir=uploads
app.upload.images=images

### SWAGGER ###
# Ordenar endpoints
springdoc.swagger-ui.tags-sorter=alpha
# Ordenar verbos http
springdoc.swagger-ui.operations-sorter=method
# Retraer endpoints
springdoc.swagger-ui.doc-expansion=none